### ISSUE TITLE
Andrew reports that jobs on Justin schedd's aren't starting properly

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/dist-comp#185]

**Comment by StevenCTimm** [comment]
Requested job ids and error messages if available.

This from dunegpfrontend01
[2024-10-13 15:15:08,524] ERROR: glideinFrontendElement:1886: Failed to talk to factory_pool for global info:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/glideinwms/lib/condorMonitor.py", line 695, in fetch_using_bindings
    results = collector.query(adtype, constraint, attrs)
  File "/usr/lib64/python3.9/site-packages/htcondor/_lock.py", line 70, in wrapper
    rv = func(*args, **kwargs)
htcondor.HTCondorIOError: Failed communication with collector.

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/glideinwms/frontend/glideinFrontendElement.py", line 1877, in query_globals
    factory_globals_dict = glideinFrontendInterface.findGlobals(
  File "/usr/lib/python3.9/site-packages/glideinwms/frontend/glideinFrontendInterface.py", line 169, in findGlobals
    status.load(status_constraint)
  File "/usr/lib/python3.9/site-packages/glideinwms/lib/condorMonitor.py", line 576, in load
    self.stored_data = self.fetch(constraint, format_list)
  File "/usr/lib/python3.9/site-packages/glideinwms/lib/condorMonitor.py", line 675, in fetch
    return CondorQuery.fetch(self, constraint=constraint, format_list=format_list)
  File "/usr/lib/python3.9/site-packages/glideinwms/lib/condorMonitor.py", line 506, in fetch
    raise QueryError(err_str) from ex

**Comment by StevenCTimm** [comment]
so there's a problem communicating to the new OSG factory.
Will see if anyone's watching on OSG slack over the weekend, and open a ticket.

**Comment by StevenCTimm** [comment]
the condor_status -any output from gfactory-1.osg-htc.org
shows that it is up but the factory on it is not.

**Comment by StevenCTimm** [comment]
[https://support.opensciencegrid.org/support/tickets/public/762ff6980c053fcf974e5bc9eb3cf7807a6946123a334a49299a33d275cef755](https://urldefense.proofpoint.com/v2/url?u=https-3A__support.opensciencegrid.org_support_tickets_public_762ff6980c053fcf974e5bc9eb3cf7807a6946123a334a49299a33d275cef755&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=10BCTK25QMgkMYibLRbpYg&m=1fWs10v0F9_YYueKwPVziMvfdRjhqkKAwoAVy7eeSyc4GpG5CiKkPRBAxOnm_8RD&s=jP_f1Z-zgVAsn6fM3ZmmRHKgGR0wgpC7Zr4IDlAOO1I&e=)

**Comment by StevenCTimm** [comment]
osg ticket 77867 is filed, see above url

**Comment by StevenCTimm** [comment]
It's back. Closing this.
